name: flashy
description: Cross-platform P2P file transfer app — send files directly between devices.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  convert: ^3.1.1
  cryptography: ^2.5.0
  flutter_secure_storage: ^10.1.0
  web_socket_channel: ^3.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.0
  multicast_dns: ^0.3.2+2
  file_picker: ^8.0.0
  google_fonts: ^6.2.1
  sqflite_common_ffi: ^2.3.4
  sqlite3_flutter_libs: ^0.5.24
  firebase_core: ^3.8.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  google_sign_in: ^6.2.2
  open_filex: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

hooks:
  user_defines:
    sqlite3:
      source: system
      name: sqlite3
