import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import '../identity/keypair_manager.dart';
import '../signaling/signaling_client.dart';
import '../storage/local_database.dart';

/// Callback when pairing completes.
typedef PairingCallback = void Function(bool success, String deviceName);

/// Orchestrates the secure pairing process between two devices.
class PairingService {
  final KeypairManager identityManager;
  final SignalingClient signalingClient;
  final LocalDatabase database;

  // Track the active pairing token generated by this device
  String? _activeHostingToken;
  PairingCallback? _onPairingCompleted;
  
  StreamSubscription? _signalingSubscription;

  PairingService({
    required this.identityManager,
    required this.signalingClient,
    required this.database,
  }) {
    _startListening();
  }

  /// Device A: Requests a pairing token from the HTTP API and generates a QR payload.
  Future<String> startPairingHost(String signalingHttpUrl, PairingCallback onCompleted) async {
    _onPairingCompleted = onCompleted;
    
    // Request short-lived token from signaling server
    final client = HttpClient();
    try {
      final request = await client.postUrl(Uri.parse('$signalingHttpUrl/api/pairing/token'));
      request.headers.contentType = ContentType.json;
      request.write(jsonEncode({
        'deviceId': identityManager.identity.deviceId,
      }));
      
      final response = await request.close();
      if (response.statusCode != 200) {
        throw HttpException('Server returned status code ${response.statusCode}');
      }
      
      final responseBody = await response.transform(utf8.decoder).join();
      final data = jsonDecode(responseBody) as Map<String, dynamic>;
      
      final token = data['token'] as String;
      _activeHostingToken = token;

      // QR format: flashy://pair?id=<deviceId>&name=<deviceName>&key=<publicKey>&token=<token>
      final uri = Uri(
        scheme: 'flashy',
        host: 'pair',
        queryParameters: {
          'id': identityManager.identity.deviceId,
          'name': identityManager.identity.deviceName,
          'key': identityManager.publicKeyHex,
          'token': token,
        },
      );
      
      return uri.toString();
    } finally {
      client.close();
    }
  }

  /// Device B: Initiates pairing by parsing scanned QR payload and sending request.
  Future<void> scanAndPair(String qrCode, PairingCallback onCompleted) async {
    final uri = Uri.parse(qrCode);
    if (uri.scheme != 'flashy' || uri.host != 'pair') {
      throw const FormatException('Invalid QR code format');
    }

    final hostId = uri.queryParameters['id']!;
    final hostName = uri.queryParameters['name']!;
    final hostKeyHex = uri.queryParameters['key']!;
    final token = uri.queryParameters['token']!;

    // 1. Generate mutual authentication signature: sign (token + myDeviceId)
    final message = utf8.encode(token + identityManager.identity.deviceId);
    final signature = await identityManager.sign(Uint8List.fromList(message));

    // 2. Register completion callback
    _onPairingCompleted = onCompleted;

    // 3. Send pairingRequest to the signaling server via WebSocket
    signalingClient.send('pairingRequest', {
      'token': token,
      'deviceId': identityManager.identity.deviceId,
      'deviceName': identityManager.identity.deviceName,
      'publicKey': identityManager.publicKeyHex,
      'signature': base64Encode(signature),
    });
  }

  /// Listen for WebSocket messages associated with pairing.
  void _startListening() {
    _signalingSubscription = signalingClient.incomingMessages.listen((msg) async {
      final action = msg['action'] as String?;
      final payload = msg['payload'] as Map<String, dynamic>?;
      if (action == null || payload == null) return;

      switch (action) {
        case 'pairingRequest':
          await _handlePairingRequest(payload);
          break;
        case 'pairingResponse':
          await _handlePairingResponse(payload);
          break;
      }
    });
  }

  /// Device A (Host) receives B's pairing request.
  Future<void> _handlePairingRequest(Map<String, dynamic> payload) async {
    final token = payload['token'] as String;
    if (token != _activeHostingToken) return; // Incorrect/expired token

    final deviceId = payload['deviceId'] as String;
    final deviceName = payload['deviceName'] as String;
    final publicKeyHex = payload['publicKey'] as String;
    final signatureBase64 = payload['signature'] as String;

    try {
      // 1. Verify Device B's signature (token + B's deviceId)
      final decodedKey = Uint8List.fromList(List<int>.from(RegExp(r'.{1,2}').allMatches(publicKeyHex).map((m) => int.parse(m.group(0)!, radix: 16))));
      
      final message = utf8.encode(token + deviceId);
      final signature = base64Decode(signatureBase64);
      
      final isSignatureCorrect = await KeypairManager.verify(
        Uint8List.fromList(message),
        signature,
        decodedKey,
      );

      if (!isSignatureCorrect) {
        throw const SecurityException('Invalid signature from peer');
      }

      // 2. Add B to database
      await database.addContact(
        deviceId: deviceId,
        deviceName: deviceName,
        publicKey: publicKeyHex,
      );

      // 3. Generate host's response signature: sign (token + A's deviceId)
      final responseMsg = utf8.encode(token + identityManager.identity.deviceId);
      final responseSig = await identityManager.sign(Uint8List.fromList(responseMsg));

      // 4. Send success pairingResponse
      signalingClient.send('pairingResponse', {
        'token': token,
        'success': true,
        'deviceId': identityManager.identity.deviceId,
        'deviceName': identityManager.identity.deviceName,
        'publicKey': identityManager.publicKeyHex,
        'signature': base64Encode(responseSig),
      });

      _activeHostingToken = null; // Single use token complete
      _onPairingCompleted?.call(true, deviceName);
    } catch (e) {
      signalingClient.send('pairingResponse', {
        'token': token,
        'success': false,
        'error': e.toString(),
      });
      _onPairingCompleted?.call(false, '');
    }
  }

  /// Device B (Scanner) receives A's response.
  Future<void> _handlePairingResponse(Map<String, dynamic> payload) async {
    final success = payload['success'] as bool;
    final token = payload['token'] as String;

    if (!success) {
      _onPairingCompleted?.call(false, '');
      return;
    }

    final deviceId = payload['deviceId'] as String;
    final deviceName = payload['deviceName'] as String;
    final publicKeyHex = payload['publicKey'] as String;
    final signatureBase64 = payload['signature'] as String;

    try {
      // 1. Verify Host signature (token + A's deviceId)
      final decodedKey = Uint8List.fromList(List<int>.from(RegExp(r'.{1,2}').allMatches(publicKeyHex).map((m) => int.parse(m.group(0)!, radix: 16))));
      final message = utf8.encode(token + deviceId);
      final signature = base64Decode(signatureBase64);

      final isSignatureCorrect = await KeypairManager.verify(
        Uint8List.fromList(message),
        signature,
        decodedKey,
      );

      if (!isSignatureCorrect) {
        throw const SecurityException('Invalid signature from host');
      }

      // 2. Add Host to database
      await database.addContact(
        deviceId: deviceId,
        deviceName: deviceName,
        publicKey: publicKeyHex,
      );

      _onPairingCompleted?.call(true, deviceName);
    } catch (_) {
      _onPairingCompleted?.call(false, '');
    }
  }

  /// Cleanup listeners.
  void dispose() {
    _signalingSubscription?.cancel();
  }
}

class SecurityException implements Exception {
  final String message;
  const SecurityException(this.message);

  @override
  String toString() => 'SecurityException: $message';
}
